### ISSUE TITLE
CSS and HTML only version 

### ISSUE THREAD

**Issue by Abuzeid1** [hexagoncircle/target-toggler#1]
# Using :has and  details element

### HTML
```html
<div class="container">
<details>
  <summary>
    open
  </summary>
</details>

<div>
And now for some lorem ipsum text to fill out the rest of this section. Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima dolores deserunt ducimus temporibus quas debitis voluptate placeat. Natus animi sequi aut, itaque cumque vitae explicabo illo amet, quaerat quasi quo?
</div>
</div>

``` 
### CSS
```css
.container:has(details[open]) div{
display: block;
}

.container div {
display: none;

}

```
